name: qrci
channels:
  - conda-forge
dependencies:
  - python=3.13.2
  - rdkit=2026.03.4
  - scipy=1.15.1
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - ipykernel
  - jupyterlab
  - pip
  - pip:
      - mols2grid
      - useful-rdkit-utils
